version: '2'

services:
  jupyter:
    image: jupyter/scipy-notebook:c8797824e8c0
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./scripts:/home/jovyan/notebooks/scripts:ro
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "8888:8888"

  env:
    build:
      context: .
      dockerfile: dev.dockerfile
    image: localhost/cmsc5751-project-env
    volumes:
      - .:/usr/src/app

  preprocess:
    build:
      context: .
      dockerfile: dev.dockerfile
    image: localhost/cmsc5751-project-env
    volumes:
      - ./scripts:/usr/src/app
    command: python preprocess.py

  predict:
    build:
      context: .
      dockerfile: dev.dockerfile
    image: localhost/cmsc5751-project-env
    volumes:
      - ./scripts:/usr/src/app
    command: python predict.py
